spring.application.name=blschool-intranet-login
server.port=8090

# JWT Secret
security.jwt.secret=dev-0123456789abcdef-0123456789abcdef-0123456789abcdef

# Debug logging
logging.level.org.springframework.security=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG
