spring.application.name=blschool-intranet-login

# API context path
server.servlet.context-path=/blschool-login/api

# DataSource
spring.datasource.url=${DBCP_BLSCHOOL_URL:jdbc:postgresql://localhost:5432/blschooldb}
spring.datasource.username=${DBCP_BLSCHOOL_USERNAME:blschooladmin}
spring.datasource.password=${DBCP_BLSCHOOL_PASS:blschooladmin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Password & JWT
security.password.mode=bcrypt
security.jwt.secret=${JWT_SECRET:change-me-please-change-me-please-change-me-please-1234567890}
security.jwt.exp-minutes=120
